import os
import threading

import faiss
import numpy as np

embedding_dim = 384  # Dimension of the embeddings generated by the model

# Absolute so the index is found no matter which directory uvicorn is started from.
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INDEX_PATH = os.environ.get("FAISS_INDEX_PATH", os.path.join(PROJECT_ROOT, "faiss_index.bin"))


def _new_index():
    return faiss.IndexIDMap(faiss.IndexFlatIP(embedding_dim))


index = _new_index()

# FAISS objects are not thread safe for concurrent writes, and uvicorn runs
# sync endpoints in a thread pool, so guard every mutation.
_lock = threading.Lock()


def add_vector(vector: list[float], doc_id: int) -> None:
    add_vectors([vector], [doc_id])


def add_vectors(vectors: list[list[float]], doc_ids: list[int]) -> None:
    if not vectors:
        return
    vec_array = np.array(vectors, dtype=np.float32)
    id_array = np.array(doc_ids, dtype=np.int64)
    with _lock:
        index.add_with_ids(vec_array, id_array)


def remove_vectors(doc_ids: list[int]) -> int:
    """Drop vectors by their SQLite ids. Returns how many were removed."""
    if not doc_ids:
        return 0
    id_array = np.array(doc_ids, dtype=np.int64)
    with _lock:
        return int(index.remove_ids(id_array))


def search_vectors(query_vector: list[float], k: int = 5) -> list[dict]:
    if k <= 0 or index.ntotal == 0:
        return []

    # Asking FAISS for more neighbours than it holds just pads with -1; clamping
    # keeps the result list honest.
    k = min(k, index.ntotal)
    query_array = np.array([query_vector], dtype=np.float32)
    similarity_scores, indices = index.search(query_array, k)

    results = []
    for score, idx in zip(similarity_scores[0], indices[0]):
        if idx == -1:
            continue
        results.append({"id": int(idx), "score": float(score)})
    return results


def get_index_size() -> int:
    return index.ntotal


def reset_index() -> None:
    global index
    with _lock:
        index = _new_index()


def save_index(path: str = INDEX_PATH) -> None:
    """Persist the index so a server restart does not wipe it."""
    with _lock:
        faiss.write_index(index, path)


def load_index(path: str = INDEX_PATH) -> bool:
    """Load a persisted index. Returns False if there is no usable file on disk."""
    global index
    if not os.path.exists(path):
        return False
    try:
        loaded = faiss.read_index(path)
    except Exception:
        return False
    if loaded.d != embedding_dim:
        return False
    with _lock:
        index = loaded
    return True
