import faiss
import numpy as np

embedding_dim = 384 # Dimension of the embeddings generated by the model
index = faiss.IndexIDMap(faiss.IndexFlatIP(embedding_dim))

def add_vector(vector: list[float], doc_id: int) -> None:
    vec_array = np.array([vector], dtype=np.float32)
    id_array = np.array([doc_id], dtype=np.int64)
    index.add_with_ids(vec_array, id_array)

def search_vectors(query_vector: list[float], k: int = 5) -> list[dict]:
    query_array = np.array([query_vector], dtype=np.float32)
    similarity_scores, indices = index.search(query_array, k)
    
    results = []
    for score, idx in zip(similarity_scores[0], indices[0]):
        if idx == -1:
            continue
        results.append({"id": int(idx), "score": float(score)})
    return results

def get_index_size() -> int:
    return index.ntotal